// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT6mjd7S1wUSnsfk6yQCOaxmQi9D0xdy4',
    appId: '1:1064287787074:web:1b177ad5974b998acf35db',
    messagingSenderId: '1064287787074',
    projectId: 'felagi-81c19',
    authDomain: 'felagi-81c19.firebaseapp.com',
    storageBucket: 'felagi-81c19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxgdbGZ0FRVLWDFyrez3k0ViJV4T3MAt4',
    appId: '1:1064287787074:android:87c5652071212c7fcf35db',
    messagingSenderId: '1064287787074',
    projectId: 'felagi-81c19',
    storageBucket: 'felagi-81c19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLaRqGN-E6-POs31kaYBe5Ldu6y3XGMK4',
    appId: '1:1064287787074:ios:f9e5270044b9ec68cf35db',
    messagingSenderId: '1064287787074',
    projectId: 'felagi-81c19',
    storageBucket: 'felagi-81c19.firebasestorage.app',
    iosBundleId: 'com.example.felagi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLaRqGN-E6-POs31kaYBe5Ldu6y3XGMK4',
    appId: '1:1064287787074:ios:f9e5270044b9ec68cf35db',
    messagingSenderId: '1064287787074',
    projectId: 'felagi-81c19',
    storageBucket: 'felagi-81c19.firebasestorage.app',
    iosBundleId: 'com.example.felagi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT6mjd7S1wUSnsfk6yQCOaxmQi9D0xdy4',
    appId: '1:1064287787074:web:47a6003a77f59f43cf35db',
    messagingSenderId: '1064287787074',
    projectId: 'felagi-81c19',
    authDomain: 'felagi-81c19.firebaseapp.com',
    storageBucket: 'felagi-81c19.firebasestorage.app',
  );
}
